env: 
  global: 
  - secure: I3VlcSE8pKDMlZXPXDQQzaO6BCNdWMQsMMfmJqyx4CaeXGFqvYDOlhRyxZgLZLZ1JQ08yeNKU/x266PQTRWnEHNOzKnE1ERvMYbKAkJlDtITca12Szwp03n3sNLu0veHv0qWR0LHw0zdzaVgTrPTe2Rh5AmhrLD774EFMNURWuQ=
language: php

php: 
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev

script: phpunit

after_script:
  - export POST_BUILD=true
  - wget http://pear.phpunit.de/get/phploc.phar
  - php phploc.phar src/ > build/result/phploc.txt
  - wget https://github.com/downloads/apigen/apigen/ApiGen-2.8.0-standalone.zip --no-check-certificate
  - unzip ApiGen-2.8.0-standalone.zip
  - rm ApiGen-2.8.0-standalone.zip
  - php apigen/apigen.php --source src/ --destination build/result/docs/ --template-config apigen/templates/bootstrap/config.neon
  - bash ./build/scripts/push_to_gh_pages.sh